import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {
  Navbar,
  Card,
  Row,
  Col,
  Container,
  Button,
  Input,
  Spacer,
  Text,
  Link,
  useTheme
} from '@nextui-org/react';


const Home: NextPage = () => {

  const { theme } = useTheme();

  return (
    <div>
      <Head>
        <title>NextUI | Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        fluid
        as="main"
        display="flex"
        direction="column"
        justify="flex-start"
        alignItems="center"
        style={{ height: '100vh', margin: 0, width: '100vw'}}
        css={{background: '#16181A'}}
        // color="$colors$secondary" does not work
      >
 
      <Navbar isCompact isBordered variant="static" style={{boxSizing: "border-box", margin: 0, maxWidth: '100%', color: theme?.colors.secondary.value,
          fontSize: theme?.fontSizes.md.value, fontWeight: theme?.fontWeights.hairline.value,
          padding: `${theme?.space['xs'].value} ${theme?.space[4].value}`}}>
        <Navbar.Brand>
          <Text b color="inherit" hideIn="xs" css={{font: theme?.fonts.sans, fontSize: theme?.fontSizes['4xl'].value, fontWeight: theme?.fontWeights.black.value}}>
            CryptoDevs
          </Text>
        </Navbar.Brand>
        <Navbar.Content hideIn="xs" variant="highlight-rounded">
          <Navbar.Link isActive href="#">Whitelist</Navbar.Link>
          <Navbar.Link href="#">NFT Drop</Navbar.Link>
          <Navbar.Link href="#">Smart Contracts</Navbar.Link>
        </Navbar.Content>
        <Navbar.Content>
          <Navbar.Item>
            <ConnectButton/>
          </Navbar.Item>
        </Navbar.Content>
      </Navbar>
 
        <Spacer />
        <Spacer />
        <Container xl>
          
          <Card css={{ $$cardColor: 'black', mw: "600px", minw: "400px"}}>
            <Card.Header css={{  position: "static", zIndex: 1, top: 5 }}>
              <Col>
                <Text size={12} weight="bold" transform="uppercase" color="#ffffffAA">
                  Initial Coin Offering
                </Text>
                <Text h4 color="white">
                  Buy CryptoDevs Tokens
                </Text>
              </Col>
            </Card.Header>
            <Card.Body>
              <Row justify="center" align="center">
                <Text h6 size={15} color="white" css={{ m: 0 }}>
                  NextUI gives you the best developer experience with all the features
                  you need for building beautiful and modern websites and
                  applications.
                </Text>
              </Row>
            </Card.Body>
        </Card>
        </Container>
      </Container>
    </div>
  );
};

export default Home;
